CREATE DATABASE xb-prof;

CREATE TABLE professionals(
    id VARCHAR(255) PRIMARY KEY NOT NULL,
    username VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    cpf BIGINT NOT NULL,
    birthdate VARCHAR(255) NOT NULL,
    whatsapp BIGINT NOT NULL,
    homephone BIGINT,
    workphone BIGINT,
    otherphones BIGINT[],
    instagram VARCHAR(255),
    facebook VARCHAR(255),
    youtube VARCHAR(255),
    tiktok VARCHAR(255),
    twiter VARCHAR(255),
    linkedin VARCHAR(255),
    clubhouse VARCHAR(255),
    cep BIGINT NOT NULL,
    street VARCHAR(255) NOT NULL,
    adressnumber INTEGER NOT NULL,
    complement VARCHAR(255),
    district VARCHAR(255) NOT NULL,
    county VARCHAR(255) NOT NULL,
    adressstate VARCHAR(255) NOT NULL,
    coutry VARCHAR(255) NOT NULL,
    actuationfields TEXT[],
    skills TEXT[],
    experiencelevel VARCHAR(255) ,
    portifoliourl VARCHAR(255),
    about TEXT,
    pictureurl VARCHAR(255),
    userpassword  VARCHAR(255)
);

INSERT INTO professionals
(
    id,
    username,
    email,
    cpf,
    birthdate,
    whatsapp,
    homePhone,
    workPhone,
    otherPhones,
    instagram,
    facebook,
    youtube,
    tiktok,
    twiter,
    linkedin,
    clubhouse,
    cep,
    street,
    adressNumber,
    complement,
    district,
    county,
    adressState,
    coutry,
    actuationFields,
    skills,
    experienceLevel,
    portifolioUrl,
    about,
    pictureUrl,
    userPassword
)
VALUES
(
    "1234665",
    'Renato',
    'email@email',
    33312198860,
    '26/07/1985',
    11972480007,
    1127055862,
    1125478953,
    '{1,2,3}',
    'instagram',
    'facebook',
    'youtube',
    'tiktok',
    'twiter',
    'linkedin',
    'clubhouse',
    3245160,
    'Ataulfo Alves',
    178,
    'sem',
    'district',
    'São Paulo',
    'São Paulo',
    'Brasil',
    '{'1','2','3','4'}',
    '{"1","2","3","4"}',
    'expert',
    'portifolioUrl.com',
    'nothing to say',
    'pictureUrl.com',
    'abc123'
) RETURNING *;

INSERT INTO professionals
(
    id,
    username,
    email,
    cpf,
    birthdate,
    whatsapp,
    homephone,
    workphone,
    otherphones,
    instagram,
    facebook,
    youtube,
    tiktok,
    twiter,
    linkedin,
    clubhouse,
    cep,
    street,
    adressnumber,
    complement,
    district,
    county,
    adressstate,
    coutry,
    actuationfields,
    skills,
    experiencelevel,
    portifoliourl,
    about,
    pictureurl,
    userpassword
)
VALUES
(
    "1e875690-7386-11eb-8eef-079e173843d9",
    "Renato Lima Santos",
    "renato@gmail.com",
    33312198861,
    "26/07/1985",
    27055862,
    22224444,
    11972480007,
    '{12356, 158746325}',
    "insta.com",
    "fb.com",
    "yt.com",
    "tktk.com",
    "tt.com",
    "lkd.com",
    "cb.com",
    "03245160",
    "Ataulfo Alves",
    178,
    "sem",
    "Vila Indústrial",
    "São Paulo",
    "São Paulo",
    "Brasil",
    '{"design", "programação"}',
    '{"logo", "backend"}',
    "avançado",
    "www.test.com.br",
    "bla bla bla",
    "www.minha.foto.com",
    "$2b$12$BiUKCu/Ah4G1x4tYQPsrOec0gvQ1vEmi63Q8a5jEp0gljb3ldQMzi"
) RETURNING *;
