module.exports = {
    professional : {
        name: 'name',
        email: 'email',
        cpf: 'cpf',
        birthdate: 'birthdate',
        whatsapp: 'whatsapp',
        homePhone: 'homePhone',
        workPhone: 'workPhone',
        otherPhones: 'otherPhones',
        instagram: 'intagram',
        facebook: 'facebook',
        youtube: 'youtube',
        tiktok: 'tiktok',
        twiter: 'twiter',
        linkedin: 'linkedin',
        clubhouse: 'clubhouse',
        cep: 'cep',
        street: 'street',
        number: 'number',
        complement: 'complement',
        district: 'district',
        county: 'county',
        state: 'state',
        coutry: 'country',
        actuationFields: 'actuationFields',
        skills: 'skills',
        experienceLevel: 'experienceLevel',
        portifolioUrl: 'portifolioUrl',
        about: 'about',
        pictureUrl: 'pictureUrl',
        password: 'password'
    }
}