module.exports = {
    locale: 'pt-BR',
    professional : {        
        id: 'id',
        username: 'username',
        email: 'email',
        cpf: 'cpf',
        birthdate: 'birthdate',
        whatsapp: 'whatsapp',
        homePhone: 'homePhone',
        workPhone: 'workPhone',
        otherPhones: 'otherPhones',
        instagram: 'instagram',
        facebook: 'facebook',
        youtube: 'youtube',
        tiktok: 'tiktok',
        twiter: 'twiter',
        linkedin: 'linkedin',
        clubhouse: 'clubhouse',
        cep: 'cep',
        street: 'street',
        adressNumber: 'adressNumber',
        complement: 'complement',
        district: 'district',
        county: 'county',
        adressState: 'adressState',
        coutry: 'country',
        actuationFields: 'actuationFields',
        skills: 'skills',
        experienceLevel: 'experienceLevel',
        portifolioUrl: 'portifolioUrl',
        about: 'about',
        pictureUrl: 'pictureUrl',
        userPassword: 'userPassword'
    },
    responseMessages: {
        USER_SAVED: 10,
        USER_LOADED: 11,
        USER_ALREADY_EXIST: 12,
        USER_NOT_FOUND: 13,
        PASSWORD_MISMATCH: 14,
        USER_AUTHENTICATED: 15,        
    },
    privateKey: "2812a7a341e863e76dad78e0ea8be22e",
}